name: CI

on:
  push:
    branches:
      - master

env:
  CONTAINER_NAME: "careerportal-front"

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        # key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        envs: CONTAINER_NAME
        script: |
          # Go to project directory
          cd  your-work-frontend/

          # Update local project from remote repository
          git pull

          # Stop current project container
          docker stop $(echo $CONTAINER_NAME)

          # Remove old container
          docker rm $(echo $CONTAINER_NAME)

          # Build new docker iamge
          docker build -f Dockerfile -t dockerized-react

          # Run new docker image in the background
          docker run -p 3000:80 -d --name $(echo $CONTAINER_NAME) dockerized-react
